// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dibxmyjrcqvlhjjndmsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpYnhteWpyY3F2bGhqam5kbXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzE0NDEsImV4cCI6MjA2MDY0NzQ0MX0.on6xulAw-vkLjK40MXmPtQk7vD-HddeNZhbz8qUOPGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);